### ISSUE TITLE
Having trouble compiling program - Can you help me?

### ISSUE THREAD

**Issue by giannissc** [xi-editor/druid#1017]
error: failed to select a version for `js-sys`.
    ... required by package `instant v0.1.4`
    ... which is depended on by `druid v0.6.0 (https://github.com/xi-editor/druid.git#8e46a06b)`
    ... which is depended on by `place-route-ui v0.1.0 (C:\Users\s1408689\OneDrive - University of Edinburgh\PhD Project\Fluego\fluego-place-route\place-route-ui)`
versions that meet the requirements `= 0.3.36` are: 0.3.36

all possible versions conflict with previously selected packages.

  previously selected package `js-sys v0.3.40`
    ... which is depended on by `druid-shell v0.6.0 (https://github.com/xi-editor/druid.git#8e46a06b)`
    ... which is depended on by `druid v0.6.0 (https://github.com/xi-editor/druid.git#8e46a06b)`
    ... which is depended on by `place-route-ui v0.1.0 (C:\Users\s1408689\OneDrive - University of Edinburgh\PhD Project\Fluego\fluego-place-route\place-route-ui)`

failed to select a version for `js-sys` which could resolve this conflict

**Comment by xStrom** [comment]
Try deleting your `Cargo.lock` file and attempt compiling again after that. If it still fails, then please show your full `Cargo.toml` file and the full command of how you are compiling.

**Comment by giannissc** [comment]
Thanks you very much @xStrom you suggestion solved the issue. I have also managed to get it working by switching from git source to crates.io
