### ISSUE TITLE
Animated background

### ISSUE THREAD

**Issue by ul** [xi-editor/druid#1020]
I'm implementing a simple oscilloscope rendered as a background of a specialised text editor. Please see the attached screenshot to get an idea of how it looks like.

This is a highly dynamic element; I aim 60fps for its update. I implemented it as a separate widget, but I was unable to make it re-painted without re-painting the editor widget. Is it because oscilloscope invalidates the same region on its paint?

Druid can keep up with updates, but because it has to re-paint the editor, it's very CPU-intensive because of the cost of text rendering (I cache font itself, but it's not enough).

Could you please recommend a way to approach this problem?

![Screen Shot 2020-06-04 at 22 04 46](https://user-images.githubusercontent.com/233227/83826938-84619080-a720-11ea-81b3-060b8275b21f.png)

**Comment by Finnerale** [comment]
> Is it because oscilloscope invalidates the same region on its paint?

Yes, I think that's what's happening.

>  I was unable to make it re-painted without re-painting the editor widget.

I don't think you can avoid that right now, as long as the editor is on top of the animation. What would be required are 'layers', which would allow the editor to draw onto its own layer and then reuse that. But to my knowledge neither Piet nor Druid support that yet.

> Could you please recommend a way to approach this problem?

I think for now you would either have to separate the editor and the oscilloscope, or live with the CPU usage. Once we have support for layers or GPU rendering (or both?), I would expect this problem to go away as well.

**Comment by ul** [comment]
Thank you for the response! I moved oscilloscope into a separate window for now and I will stay tuned on updates about layers.

**Comment by cmyr** [comment]
@ul just to check, are you caching the text layout objects themselves? You shouldn't need to rebuild them between paints unless data changes.

**Comment by ul** [comment]
I was not caching layout, only font. Thanks for the hint!
