### ISSUE TITLE
druid-derive: syn::ty::Type` doesn't implement `std::fmt::Debug

### ISSUE THREAD

**Issue by Arifd** [xi-editor/druid#1024]
I couldn't get any Druid project to compile. Was getting some kind of linker error. I went through the crates one by one, attempting to find out where it was breaking.

If I put `druid-derive = "0.3.1"` into my Cargo.toml dependencies, and try to run nothing but an empty `main()`. This is the error I get:

```
   Compiling druid-derive v0.3.1
error[E0277]: `syn::ty::Type` doesn't implement `std::fmt::Debug`
  --> /home/arif/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-derive-0.3.1/src/attr.rs:65:5
   |
65 |     pub ty: syn::Type,
   |     ^^^^^^^^^^^^^^^^^ `syn::ty::Type` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `syn::ty::Type`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `&syn::ty::Type`
   = note: required for the cast to the object type `dyn std::fmt::Debug`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `syn::expr::ExprPath` doesn't implement `std::fmt::Debug`
  --> /home/arif/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-derive-0.3.1/src/attr.rs:69:5
   |
69 |     pub same_fn: Option<ExprPath>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `syn::expr::ExprPath` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `syn::expr::ExprPath`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `std::option::Option<syn::expr::ExprPath>`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `&std::option::Option<syn::expr::ExprPath>`
   = note: required for the cast to the object type `dyn std::fmt::Debug`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Finnerale** [comment]
That's odd, everything is working on my end.
Maybe try `cargo clean` or deleting the `Cargo.lock` file, this seems like something is awry on your machine.

**Comment by Arifd** [comment]
Well that's very strange. I tried your suggestions, but in the end, If I delete both derive debugs on `Field` and `Fields` (lines 62 and 32 of attr.rs) My end is happy again. I was then able to put `druid` back into my dependencies, and everything works A-OK now. :)

**Comment by Finnerale** [comment]
Hmm, have you tried druid with no other dependencies? Or running the examples from the repo?

**Comment by Arifd** [comment]
Yep. That's what I'm doing, running only the first example from: https://xi-editor.io/druid/get_started.html

Nothing else.

**Comment by jneem** [comment]
I couldn't reproduce this with a fresh druid project. Could you share your Cargo.lock?

In case it's relevant, cargo has pulled in version 1.0.30 of syn, and it's `Type` [appears to implement Debug](https://docs.rs/syn/1.0.30/syn/enum.Type.html)

**Comment by Arifd** [comment]
relevant section of Cargo.lock:
```
[[package]]
name = "syn"
version = "1.0.30"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "93a56fabc59dce20fe48b6c832cc249c713e7ed88fa28b0ee0a3bfcaae5fe4e2"
dependencies = [
 "proc-macro2",
 "quote",
 "unicode-xid",
]
```

Full cargo.lock: https://pastebin.com/Pt7p20C2

**Comment by Finnerale** [comment]
Even when I use that same `Cargo.lock`, everything builds just fine.
Are you using the latest stable version of Rust as well?

**Comment by Arifd** [comment]
This is my `rustc -- version`: rustc 1.46.0-nightly (fd4b177aa 2020-06-08)

**Comment by Finnerale** [comment]
Ok, can you check what happens with 1.44.0 (stable)?

**Comment by Finnerale** [comment]
I tested it with the 2020-06-05 and 2020-06-09 on my machine just now and everything is working.

**Comment by Arifd** [comment]
Okay, I will `rustup update` create a new project just to see if anything is different this time.
Then I will downgrade to 1.44.0 (stable) and do the same.

I will edit this post to let you know, once it's all done.

**Comment by Arifd** [comment]
Well it just gets weirder:

`rustc 1.46.0-nightly (feb3536eb 2020-06-09)`: ran, no problems.
`rustc 1.44.0 (49cae5576 2020-06-01)` ran, no problems. 

I guess this problem is ... resolved! ¯\\_(ツ)_\/¯

**Comment by Finnerale** [comment]
Good to hear it works now :+1: 
It probably was some bug with that specific nightly version.

**Comment by dvof** [comment]
Hey guys, similar issue. When I clone the repo and build it from within the `druid` folder or `druid/druid-derive` folder it compiles without issue:
```
   Compiling proc-macro2 v1.0.56
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling syn v1.0.109
   Compiling druid-derive v0.5.0 (C:\Users\daanv\Projects\druid\druid-derive)
    Finished dev [unoptimized + debuginfo] target(s) in 3.16s
```

Now, when I'm doing basically the same thing, creating a new package somewhere else (not in the repo) `cargo new test_druid` and add one dependency `druid-derive` I get a bunch of similar errors.

New package `cargo.toml`:
```
[package]
name = "test_druid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid-derive = { path = "../druid/druid-derive" }
```

The compile errors:
```
    Updating crates.io index
   Compiling proc-macro2 v1.0.56
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling syn v1.0.109
   Compiling druid-derive v0.5.0 (C:\Users\daanv\Projects\druid\druid-derive)
error[E0277]: `syn::Type` doesn't implement `Debug`
  --> C:\Users\daanv\Projects\druid\druid-derive\src\attr.rs:66:5
   |
63 | #[derive(Debug)]
   |          ----- in this derive macro expansion
...
66 |     pub ty: syn::Type,
   |     ^^^^^^^^^^^^^^^^^ `syn::Type` cannot be formatted using `{:?}` because it doesn't implement `Debug`
   |
   = help: the trait `Debug` is not implemented for `syn::Type`
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `ExprPath` doesn't implement `Debug`
  --> C:\Users\daanv\Projects\druid\druid-derive\src\attr.rs:75:12
   |
71 | #[derive(Debug, PartialEq, Eq)]
   |          ----- in this derive macro expansion
...
75 |     SameFn(ExprPath),
   |            ^^^^^^^^ `ExprPath` cannot be formatted using `{:?}` because it doesn't implement `Debug`
   |
   = help: the trait `Debug` is not implemented for `ExprPath`
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `==` cannot be applied to type `ExprPath`
  --> C:\Users\daanv\Projects\druid\druid-derive\src\attr.rs:75:12
   |
71 | #[derive(Debug, PartialEq, Eq)]
   |                 --------- in this derive macro expansion
...
75 |     SameFn(ExprPath),
   |            ^^^^^^^^
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `ExprPath: std::cmp::Eq` is not satisfied
   --> C:\Users\daanv\Projects\druid\druid-derive\src\attr.rs:75:12
    |
71  | #[derive(Debug, PartialEq, Eq)]
    |                            -- in this derive macro expansion
...
75  |     SameFn(ExprPath),
    |            ^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `ExprPath`
    |
note: required by a bound in `AssertParamIsEq`
   --> C:\Users\daanv\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\cmp.rs:315:31
    |
315 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0369.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `druid-derive` due to 4 previous errors
```

When getting the rustc and cargo version they're identical in both projects, I also upgraded them to the latest version:
```
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Pro) [64-bit]
```

I removed the Cargo.lock a few times with no effect, and when I try to build the repo directly from github (by just adding `druid = "0.8.3"`) it also fails with the same errors. Older versions like 0.7.0 do compile. 

It is very strange that building it inside the repo works, but when adding it as a dependency in another project it fails. I feel like something buggy is going on with the compiler or file dependency manager. Does anyone have a quick fix?

**Comment by xStrom** [comment]
This seems the same as #2373. This should be fixed in `master` but there is no new `druid-derive` release yet, pending #2377.

It works inside the repo because the `tracing` crate enables the `extra-traits` feature on `syn`. #2375 enabled this feature for `syn` in all cases, which should be the fix.
