### ISSUE TITLE
Ability to customize individual instances of widgets

### ISSUE THREAD

**Issue by rhzk** [xi-editor/druid#1032]
There should be a option to change the looks for individual instances of widgets.
Two solutions comes to mind, we could have a style object that describes the widgets look
and a option to create the widget with that style, for example:

let custom_style = { border_size : 0.0, background_color : red, default...}

Label::new() // Default style
Label::new_with_style(custom_style)

Or we could have a trait that each widget implements:

fn border_size()
fn border_color()
..

Personally I like the first option, it should also be quicker to implement

**Comment by Finnerale** [comment]
I think what you want is already available with `Env` and composition, see this [Zulip discussion](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/Question.20about.20the.20TextBox).

**Comment by rhzk** [comment]
I see its implemented for label, but for textbox the values are hard coded.
Thats why I was thinking to have some interface for all Widgets

**Comment by Finnerale** [comment]
Well, if they don't work, they just have not been moved to `Env` yet. So feel free to open a PR that moves those values to `Env` instead of using constants.

**Comment by rhzk** [comment]
Maybe I am wrong but is not Env values global for all instances? So when I change background color for a textbox in Env it will change all the textboxes background color.

**Comment by Finnerale** [comment]
Oh, that's what [`EnvScope`](https://docs.rs/druid/0.6.0/druid/widget/struct.EnvScope.html) is for. It allows you to override `Env` variables for a sub tree of widgets.

**Comment by rhzk** [comment]
Ahh thank you, had no idea you could overwrite it for specific widgets
