### ISSUE TITLE
Cache piet::Image in Image widget

### ISSUE THREAD

**Issue by eliemichel** [xi-editor/druid#1035]
Using the [`image`](https://github.com/xi-editor/druid/blob/master/druid/examples/image.rs) example with a large image is insanely slow.

A first read may suggest that the problem is in repeating `ctx.make_image` at each `paint` event, is there a way to cache this and reuse the image from the previous frame? Since it depends on the `PaintCtx` I'm not sure how to do it.

**Comment by cmyr** [comment]
Yes, caching makes sense. We haven't done a ton of work with image stuff, and there should probably be a way to get images outside of `paint()`, but I do think that the `Image` widget should be caching the `PietImage` data between paint calls. If you're interested in doing a PR this should be quite straight forward, happy to answer any questions here (or you can jump on the zulip) if you run into any problems. :)

**Comment by eliemichel** [comment]
Ok, sbdy was quicker, thanks @jpochyla ^^
