### ISSUE TITLE
use text measurement to determine label width

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#111]
this is currently hard-coded.

I think `Label` and `DynLabel` should also get moved into their own file.

**Comment by andlr** [comment]
[This](https://github.com/xi-editor/druid/compare/master...andlr:label-width) gets the work done, but I am not sure if it is okay to use hard-coded `font_size` in both `paint` and `layout` methods.

**Comment by cmyr** [comment]
@andir feel free to open a PR! keeping font_size hard-coded for now is okay, we can figure that out later.

**Comment by LiHRaM** [comment]
Is this closed then, or are we using this to track the work on `font_size`?
