### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by jjl** [xi-editor/druid#128]
Hi Raph,

I thought i'd have a go at making druid work with wasm, since piet appears to support it (although curiously with the `web` feature rather than selecting by target architecture?).

druid-shell brings up 8 errors when i try and do it there. my gut feeling is that this is probably not the place to make the change, since the errors are for `Window`, `WindowBuilder` etc.
Trying to make the changes in in druid itself is definitely less good, with rustc giving up after 200 errors.

I know you've said it's probably a bit early to be worrying about too many backends, but given the logistical differences with this one, i thought it would be a good test of druid's design.

I'm willing to continue with the work as i'm able, but i think i'm going to need some guidance on the best way to go about it to get any further.

**Comment by raphlinus** [comment]
You probably want to start with #30, as it has been working at some point.

The piet-common layer should be selecting the web backend automatically with the wasm32 target.

**Comment by jjl** [comment]
After a rebase, this branch seems to compile and run in the browser. Numbers and clearing seem to work, but there's what looks like a width calculation problem, so I can't try arithmetic operations because they're clipped. Going to look into that

**Comment by jjl** [comment]
investigation shows this was related to DPI - specifically that [canvas defaults to 96dpi](https://stackoverflow.com/a/26047748). I'm going to try and enable a high-dpi canvas with this technique, but setting dpr to 1 makes it render correctly at lower dpi.
