### ISSUE TITLE
Cross Platform `WinHandler`

### ISSUE THREAD

**Issue by rylev** [xi-editor/druid#13]
With #11 drawing will be cross platform. The question is then "what next?". I propose we next try to make `WinHandler` cross platform. `WinHandler` is the trait that defines how to respond to window events like painting, size changes and keyboard/mouse events. 

Here's a list of items that need to be addressed:
* `WinHandler::connect` takes a `WindowHandle` which has a weak reference to a `WindowState` which is highly Windows specific as it has a reference to `HWND` and `WndProc`. `connect` stores the `WindowHandle` on the state's `LayoutContext`. The handle is used for the following: invalidating widgets, closing the window, file dialog, converting physical pixels to px units, getting the current dpi. Perhaps this can all be abstracted away in a trait that is made concrete in a similar way that we do with `piet-common`
* The various keyboard handlers take modifier keys which can be different on different platforms. We could solve this the same way web APIs do: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState
* Realted to the first issue: `WinHandler::mouse`, `WinHandler::mouse_move` and `WinHandler::size` all use the windows specific `WindowHandle` that is stored on the `UiState`'s `LayoutContext`
* `WinHandler::destroy` calls the windows specific `win_main::request_quit()`

Thoughts on how to abstract `WindowHandle` and how to handle modifier keys?

**Comment by raphlinus** [comment]
Closing this, as we've been cross platform for a while, and I think all other relevant details are captured in other issues.
