### ISSUE TITLE
Make warnings fail CI

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#139]
We have an informal policy not to commit code that prints warnings; it would be nice to make this an official policy, by baking it into CI.

If anyone wants to dig into this, that would be very welcome!

**Comment by LiHRaM** [comment]
This could be pretty easily implemented by adding `#![deny(warnings)]` to the top of `lib.rs`. 
That way we enforce the policy locally as well, which might reduce the time newcomers spend trying to figure out why the CI is failing. Thoughts?

**Comment by raphlinus** [comment]
Hmm, I'm not sure. It seems more fragile, like if a brand-new rustc starts throwing a warning (for example, as happened with `dyn Trait`). One of the crates I work on has a no-warnings policy, but I can't remember which one; sadly, there's very little consistency in CI setups :/

**Comment by LiHRaM** [comment]
A fair point. Steve Klabnik suggests `cargo rustc -- -D warnings` on the command line for the same behavior [here](https://www.reddit.com/r/rust/comments/8oz7md/make_cargo_fail_on_warning/), which I think is the cleanest alternative.

But that doesn't really solve the problem, unless we start pinning that CI template to versions (as opposed to stable/nightly).

**Comment by cmyr** [comment]
The reason not to like `#![deny(warnings)]` is because warnings are totally reasonable during development; we just don't want them in code we commit. I think that `cargo rustc -- -D warnings` (only on stable) is the correct approach; if we have to fix some warnings every six weeks that's manageable.
