### ISSUE TITLE
argument ordering of Widget methods is inconsistent

### ISSUE THREAD

**Issue by jjl** [xi-editor/druid#154]
`event`, unlike the other methods, takes the event before the context, which sticks out a bit. It should use the same order as the others for consistency

**Comment by raphlinus** [comment]
This feels minor, but is one of those things that's probably easier to fix now than later. I'll accept a PR, though it'll cause merge conflicts with other in-flight PR's, notably multi-window and gtk.

**Comment by jjl** [comment]
> On 15 Sep 2019, at 18:47, Raph Levien <notifications@github.com> wrote:
> This feels minor, but is one of those things that's probably easier to fix now than later. I'll accept a PR, though it'll cause merge conflicts with other in-flight PR's, notably multi-window and gtk.
> 
I’m unlikely to get to it before the multi-window is merged (at least I hope that’ll be done before it), at which point I’ll update it along with the web backend.

/j

**Comment by cmyr** [comment]
fixed in #317
