### ISSUE TITLE
Building on Mac (troubleshooting)

### ISSUE THREAD

**Issue by sombrastudios** [xi-editor/druid#155]
First, I hope the title isn't confusing. I wasn't quite sure, what the right description of this might be.

There's a small problem when building this on mac.
A lot of people will have `libffi` installed via `homebrew`, this causes a little problem.

An Error message pops up, stating that `pkg-config` is not able to locate `libffi`

this can be fixed fairly easily using this command here:

`export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig`

Now `pkg-config` will find the ffi library and one is ready to have a good time playing around with druid and the examples!

Discussion:
Add a troubleshooting section to the readme

**Comment by cmyr** [comment]
This is covered in `CONTRIBUTING.md`; maybe we should link to that document from the readme?

**Comment by sombrastudios** [comment]
I overlooked that, thanks for pointing that out.
Personally, I think that a GitHub Wiki or even more so the `README.md` would be the first place anyone would look for solutions to this kind of problem (he very much might run into, given he's using the affected platform).

Though I might be unfamiliar with existing conventions, I often find it pleasant just having to swift through the readme and be able to get a jumping start to try things out.
Having to read more files could steepen the learning curve

**Comment by cmyr** [comment]
I agree, it totally makes sense for this to be in the readme; or at the very least for the readme to link to link to `CONTRIBUTING` in a section on building. If you'd like to submit a PR I'd be happy to merge!

**Comment by sombrastudios** [comment]
I created a simple one, hope it looks fine
