### ISSUE TITLE
make LocalizedString::placeholder() take String instead of &'static str

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#159]
This will make it more useful, and cover up some current papercuts like the fact that application windows will not have useful names until we wire up more app bundle stuff.

**Comment by scholtzan** [comment]
I was digging through the code and thought I'd do something useful: https://github.com/xi-editor/druid/pull/195

**Comment by cmyr** [comment]
Thanks @scholtzan, nice to see you in here!
