### ISSUE TITLE
add option to log to stderr to AppLauncher

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#162]
This would be a builder style fn, so that you could write:

```rust
    AppLauncher::with_window(main_window)
        .print_logs(true)
        .launch(State::default())
        .expect("launch failed");
}
```

And then when we start the application we could setup a very barebones log handler that just calls `eprintln`. (@LiHRaM had something like this in an early draft of #135, which we might be able to reuse?)

**Comment by Cogitri** [comment]
Uhh... I don't think I was meant to be pinged? :)

**Comment by cmyr** [comment]
oops yes that was supposed to be @LiHRaM 😁

**Comment by LiHRaM** [comment]
I've got working code in a branch, let me get a PR up.

**Comment by LiHRaM** [comment]
@cmyr Feel free to have a look! I don't know how strongly you felt about `print_logs`, otherwise I think it is as you wanted it to be. :)
