### ISSUE TITLE
Drawing the outline of a rectangle

### ISSUE THREAD

**Issue by sombrastudios** [xi-editor/druid#187]
Hello,
this isn't as much of an issue, as it is a question.

Could you give a brief example of how to draw the outline of a rectangle inside the `paint` method of a widget?

I hope this is not the wrong place to ask this question and I don't bother the development of druid.

Thank you for reading trough this

**Comment by zaynetro** [comment]
If by outline you mean that you want to draw a rectangle with a border (or stroke the rectangle) you can use `RenderContext::stroke` or `RenderContext::stroke_styled` methods.

See example: https://github.com/xi-editor/druid/blob/master/src/widget/button.rs#L207

**Comment by sombrastudios** [comment]
Thank you, this makes things much happier for me. Glad you showed this
