### ISSUE TITLE
Run rustfmt CI action only on one host

### ISSUE THREAD

**Issue by madig** [xi-editor/druid#197]
I don't think rustfmt gives different results on different platforms, so `runs-on: ${{ matrix.os }}` can be shortened to one of the hosts. Saves CI time.

**Comment by cmyr** [comment]
My belief was that rustfmt wouldn't format code that wasn't built on the current platform, but I will investigate!

**Comment by cmyr** [comment]
edit: you're right, it seems to format everything regardless of whether it is built, so we can definitely remove the matrix. 👍

**Comment by ForLoveOfCats** [comment]
Would it be preferable to run this on a Linux platform or on one of two platforms already being used for the rustfmt job?

**Comment by cmyr** [comment]
I _assume_ linux is best for this, there should be more linux resources? Just guessing.

**Comment by ForLoveOfCats** [comment]
That's what I was also assuming when I went to look at what modifications would be required for this so I was surprised to see that it was running it on macOS and Windows but not any Linux distro which threw me off hence the question.
