### ISSUE TITLE
Scrollbar cannot be interacted with

### ISSUE THREAD

**Issue by ForLoveOfCats** [xi-editor/druid#220]
When running the `scroll` example on Linux with the just merged GTK support the scrollbar cannot be interacted with. It appears and fades away correctly, just cannot be clicked on and dragged.

**Comment by ForLoveOfCats** [comment]
I've been following both Xi and Druid for a while, I would like to take this as an opportunity to contribute in a somewhat substantial way as I have a great deal of interest in Druid on Linux.

**Comment by cmyr** [comment]
This is actually an issue with the scroll widget itself I believe, but this is definitely something we'll want to fix!

**Comment by ForLoveOfCats** [comment]
Ah! I'm going to take a look, anything to look out for?

**Comment by cmyr** [comment]
I suspect there will be some subtlety with tracking the mouse, but I would just start poking around in `src/widget/scroll.rs` and seeing how things are wired up.

**Comment by ForLoveOfCats** [comment]
So I see that a widget's input handling is done in the `event` function part of the `Widget<T>` trait and that the `Scroll<T>` widget does not handle any `Event::MouseDown`/`Event::MouseUp` events. Is this the only location where these scrollbars will ever be thus these should be handled by `Scroll<T>` or should the scrollbars instead be broken out into a separate widget handling this independently?

Has dragging on the scrollbars ever worked or is this a new feature?

**Comment by raphlinus** [comment]
This is a new feature. I think just implementing mouse events in `Scroll<T>` is probably the way to go for now. It's certainly possible to imagine breaking it out into smaller composable widgets, but it's not immediately obvious how that should go.

**Comment by ForLoveOfCats** [comment]
Copy that!

**Comment by zaynetro** [comment]
Scroll bars added in #142 . Would love to see mouse support!
