### ISSUE TITLE
High CPU usage in calculator demo

### ISSUE THREAD

**Issue by Felk** [xi-editor/druid#230]
Hi there,
I've tried running the calculator demo to see how advanced and -- more importantly -- fast this ui toolkit is. Doing that I notied that frantically moving your mouse around causes high CPU usage.

Or more formally: Causing many context invalidations, e.g. by moving the mouse around to cause many HotChanged events, I was able to get my CPU usage to about 20% (close to 1 core being exhausted). I noticed that the entire screen gets redrawn for every such event. Is this just due to imcomplete optimization, or is this by design?

**Comment by cmyr** [comment]
Thanks for your concern!

This is a matter of implementation; we'd like to prove the general approach before spending too much time optimizing. Minimal invalidation is definitely on the roadmap, though. :)

**Comment by raphlinus** [comment]
Can you share a bit more detail which platform and whether it's a debug or release build? There might be some low hanging fruit here, though @cmyr is certainly right that there's a long roadmap with all kinds of ideas for performance.

**Comment by Felk** [comment]
> which platform and whether it's a debug or release build

I originally used a debug build, but a release build behaves similarly. I'm on Windows 10.

> Minimal invalidation is definitely on the roadmap, though

> there's a long roadmap with all kinds of ideas for performance

That sounds promising! I'll keep an eye out then. Thanks for the replies, I guess I'll close this now
