### ISSUE TITLE
Support setting window size during creation

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#232]
Currently window sizes are hard-coded.

This project has two components: the first is updating the various `WindowBuilder`s in druid-shell to get `set_size()` fns, and then using those sizes when building windows. The second part is exposing this in druid; this should be similar, adding a field and a builder method to `WindowDesc` in `app.rs`.

Although this will touch a number of different files, the actual work should be straight-forward, and would be a good issue for someone curious about Druid.

**Comment by 8176135** [comment]
Do you want the width/height to be taken in as floats rather than integers? Since you are multiplying the window size by the dpi scale, floating points might actually make a difference in the size of the window.

**Comment by raphlinus** [comment]
I think floats are good, for that reason, thanks for bringing up the question.
