### ISSUE TITLE
Quit Menu item not working

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [xi-editor/druid#244]
On Mac OS Catalina 10.15 Beta, the Menu item on examples to Quit Druid is not working.

BTW: I'd like to try and help out, and on the weekend will try and take a look at this issue myself.

**Comment by cmyr** [comment]
Interesting, we aren't tested on catalina but these menu items do work on other OS's. If anyone running Catalina (@nangtrongvuon?) wants to reproduce this that would be great, and happy to have you look into this more of course. :)

**Comment by futurepaul** [comment]
Quit menu item works for me on Catalina. But now I'm very curious what went wrong!

One thing this made me notice on Catalina (not sure if this is Catalina specific) is that when I first launch the app the menu doesn't work at all. If macOS is set to "automatically show and hide the menu bar" it won't show when I put the mouse at the top of the screen. And if the menu bar is always showing, I can click on other parts of the menu but not on the Druid app's part of the menu.

But if I click out of the Druid app, then back into it, everything works fine.

**Comment by andrewdavidmackenzie** [comment]
Seems I had some problem with the Finder. Affected other apps too and I had to reboot to fix it!

I can confirm the other bug you mention: menu not working initially.

But this issue was my fault and I'll close it.

**Comment by cmyr** [comment]
@andrewdavidmackenzie glad you've got that resolved, thanks for the issue in any case.
