### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by sgehrman** [xi-editor/druid#255]
Did cargo build, now what?

**Comment by mrandri19** [comment]
you can start by running the examples by doing `cargo run --example hello`. Then if you want to build an app you can just create a file in the examples folder. [Here](https://pauljmiller.com/posts/druid-widget-tutorial.html)'s a tutorial on how to make a custom widget. If you want to use druid as a library we just released `0.3.0`: https://crates.io/crates/druid. 
If you have other questions we usually are on https://xi.zulipchat.com/.
