### ISSUE TITLE
Windows 10 : running examples : closing druid main window doesn't stop cargo.exe

### ISSUE THREAD

**Issue by LeonGGX** [xi-editor/druid#265]
Thank you for the great job you are doing in the field of Rust GUI ...

When running the examples on Windows 10, closing the main window doesn't stop cargo.exe from running. The window get closed, but the process in the back doesn't stop. You have to go to the console and use Ctrl + c to stop the process. Then you receive the following message :
error: process didn't exit successfully: `D:\...\target\debug\examples\multiwin.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
Thanks for advice.

rust version : 1.38.0

**Comment by zaynetro** [comment]
I can confirm that the same happens on macOS Mojave (10.14.6).

**Comment by cmyr** [comment]
Yea, thanks for this. It's a slightly tricky one because there are platform-specific expectations; on windows we should kill the application when the main window closes, but on mac we shouldn't.

There's a separate problem on mac where once the last window is closed the menu stops working. :/
