### ISSUE TITLE
multiwin example doesn't work as intended on linux

### ISSUE THREAD

**Issue by 8176135** [xi-editor/druid#282]
Since there is no default menu for linux in druid (see #281 ),  the multiwin example doesn't have any way to actually create more than 1 window. 

A easy fix would be to just use the windows default menu on linux, i.e.
```
fn make_menu<T: Data>(state: &State) -> MenuDesc<T> {
    let mut base = MenuDesc::empty();
    #[cfg(target_os = "macos")]
    {
        base = druid::menu::sys::mac::menu_bar();
    }
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    {
        base = base.append(druid::menu::sys::win::file::default());
    }
    ...
}
```

**Comment by cmyr** [comment]
I think this is a totally reasonable solution in the near-term, and would happily accept this PR. 😎
