### ISSUE TITLE
Textbox widget panics when appending text on windows

### ISSUE THREAD

**Issue by 8176135** [xi-editor/druid#288]
The Textbox widget panics when text is added at the end. This can be most easily seen by running the textbox example on windows, and trying to add text at the end.

This only seem to happen on Windows, and I traced it back to code in `piet-direct2d`, specifically line 622 in the `hit_test_text_position` function. 
```
&self.text[0..text_position]
```

The issue seems to be that `text_position` at line 622 increases when you type a character, but `self.text` doesn't update yet, causing an out of bounds panic.

**Comment by raphlinus** [comment]
#275 fixes this, but there might be a better solution in the works.

**Comment by 8176135** [comment]
Ah ok, I'll close this issue then
