### ISSUE TITLE
How to dynamically add widgets to the window at runtime?

### ISSUE THREAD

**Issue by 8176135** [xi-editor/druid#289]
For example, how can I create a window that has a button that can add more buttons onto the screen when pressed? 

Useful for building a basic todo app etc.

There doesn't seem to be an example with any widgets added at runtime.

**Comment by raphlinus** [comment]
This requires a container widget with dynamic behavior. Probably the canonical example of this is a List widget (which exists in prototype form, and #278 tracks getting it merged), which has a closure to create a new child widget when an item is added to the list.

Agree this is one of the things that needs good documentation, as users coming from traditional toolkits will expect an "add_widget" method, which is the main way this is done. (We might add something like that also, but as an "escape hatch" for when the data-oriented approach doesn't work well)

**Comment by zaynetro** [comment]
You can also create a custom widget that rebuilds the tree whenever data changes.

See example: https://github.com/zaynetro/sentences/blob/master/src/rebuild_wrap.rs

**Comment by cmyr** [comment]
Maybe we need a `DynChild` widget that is init'd with `needs_rebuild` and `widget_builder` closures; it would check in `update` if it needs to be rebuilt, and would replace its root by calling the builder if so.

For this to work we would probably want to finally add some `WasCreated` lifecycle event for widgets, so that they can do some setup before `layout` is called for the first time.

**Comment by raphlinus** [comment]
Yeah, I think that would be an easy on-ramp for dynamic behavior, though it is a bit limited. It should work well for widgets that are basically static (labels and the like), much less well when you need to get the data back out. From what I can see, zaynetro's `RebuildWrap` and cmyr's `DynChild` are the same thing, though maybe I'm missing something.

And yes, we need a widget-created lifecycle event. Among other uses, it's needed so a widget can claim focus on startup, and is also part of the environment optimization that's being discussed as followup for #279. Getting this right is subtle, so I'll try to think about it and at least write up a plan, if not a prototype implementation.

**Comment by zaynetro** [comment]
List widget is now in druid #278 . Can we consider this issue as closed for now?

**Comment by raphlinus** [comment]
Sure, let's close this. I think there will be a continuing demand for documentation and examples that explain how make dynamic changes to the UI, but this is a very good start.
