### ISSUE TITLE
Incorrect scaling of window contents (GTK)

### ISSUE THREAD

**Issue by katyo** [xi-editor/druid#319]
I run several examples and all looks like as here:
![image](https://user-images.githubusercontent.com/238571/69034688-b2d98180-0a03-11ea-9e43-23de46ffab57.png)
It seems window contents incorrectly scaled inside it.

My env:
```
gdk-x11-3.0     3.24.10
gdk-pixbuf-2.0  2.38.1
gdk-pixbuf-xlib-2.0     2.38.1
gtk+-3.0        3.24.10
gtk+-unix-print-3.0     3.24.10
gdk-3.0 3.24.10
gtk+-wayland-3.0        3.24.10
gdk-wayland-3.0 3.24.10
gtk+-x11-3.0    3.24.10
```

**Comment by cmyr** [comment]
I'm unable reproduce this (in a VM, debian 10.1), so I'm not sure what's going on. Wonder if this is a HIDPI issue?

**Comment by Ralith** [comment]
I observe exactly the inverse behavior on my 4k laptop: widgets are restricted to the upper-left 2/3 of the window.

**Comment by cmyr** [comment]
@katyo can you  test the patch at #347?

**Comment by katyo** [comment]
@cmyr yes, it seems looks fine now.
![image](https://user-images.githubusercontent.com/238571/69649454-e2852b00-108e-11ea-94a6-bdc40894583e.png)
