### ISSUE TITLE
Dynamic Button Text?

### ISSUE THREAD

**Issue by 8176135** [xi-editor/druid#349]
Looking at the implementation of `Button`, it seems we either need a separate `DynButton`, or make the button more generic, with a default label creation functions.

**Comment by cmyr** [comment]
yea, my feeling here is that button  should be more generic, and that the 'content' of a button should be one of a variety of things; a label, a shape, an image, a custom widget, etc; really anything that can draw itself differently based on the button's active state.

**Comment by Finnerale** [comment]
I suppose this can be closed, now that we have `Button::dynamic` and the more generic `WidgetExt::on_click`.
