### ISSUE TITLE
std::ops::Bit* for KeyModifiers?

### ISSUE THREAD

**Issue by ratmice** [xi-editor/druid#365]
I was trying to match `HotKey::new(None, "+")` or `HotKey::new(Shift, "+")`,

A thought was that perhaps we could add an `enum Modifiers { None, Cmd, Shift, Alt, Meta, Ctrl}`, then [`std::ops::BitOr`](https://doc.rust-lang.org/std/ops/trait.BitOr.html) with `type Output = KeyModifiers`, for `Modifiers`.

As well as implementing the bitwise operator traits for `KeyModifiers` with `output = KeyModifiers` for KeyModifiers?

Anyhow I haven't looked at it enough, but it seemed from `HotKey::SysMods` and `HotKey::RawMods` might benefit from an implementation based around the bitwise operator traits.

It has occurred to me that while it might be beneficial for the rust API,
that reliance on operator overloading in this way would also probably make exporting bindings to scripting languages more difficult.

Not looking into it right now, but wanted to gauge reaction and see if this has already been tried, in case it might be something I could investigate in the future.

**Comment by raphlinus** [comment]
I'm in favor, as long as we're trying this out on real-world examples to make sure it actually makes them more ergonomic. Certainly, I agree that it's possible to model modifier combinations as bit sets.

**Comment by cmyr** [comment]
It's not totally clear what this is expressing. When modifiers are expressed as bitsets, it would usually be in the sense that `RawMods::Alt & RawMods::Shift == RawMods::AltShift`. In your case, `RawMods::None & RawMods::Shift == RawMods::Shift`, which would match _only_ shift, and ignore none, which I don't think is what you're looking for?

In any case the way I would do this would just be,

```rust
match event {
    Event::KeyDown(key) if HotKey::new(None, "x").matches(key) || HotKey::new(RawMods::Shift, "x").matches(key) => (),
    _ => (),
}
```

which is slightly more verbose, but not horrible?

Anyway: I'm open to this, it just isn't intuitive what it should mean.

**Comment by ratmice** [comment]
Yeah, what you show is exactly what I ended up doing, so this isn't terribly important,
but if it could eek out an ergonomic improvement might be worthwhile.

**Comment by cmyr** [comment]
But doesn't my initial point hold? adding bitwise operators still wouldn't let you match both `None` and `Shift`.

**Comment by ratmice** [comment]
That's certainly the most straight forward implementation, but i'm not certain it has to be the case.

But i agree with your final statement "it just isn't intuitive what it should mean", It certainly seems like at the least it's going to require moving the modifier from the construction of the hotkey into Or'ing modifiers against the match In something like a builder pattern.

**Comment by cmyr** [comment]
One thing we could do is add a `matches` fn to `KeyEvent`, which takes `Into<HotKey>`; this would be slightly less verbose, i.e.

```rust
// in a match
Event(KeyUp(key)) if key.matches((SysMods::Shift, "x")) or key.matches((None, "x")) => (),
```

We could also maybe implement a `KeyMatch` trait, kind of like the [`Pattern`](https://doc.rust-lang.org/1.39.0/std/str/pattern/trait.Pattern.html) trait, so that you could match against things more complicated than a single hotkey.

**Comment by raphlinus** [comment]
I've been thinking about a KeyMatch trait and think I have figured out a clever way to make it ergonomic. Stay tuned.

**Comment by raphlinus** [comment]
I have a partial implementation in #370. There are a few TODO's. I think it's possible to go from the various concrete implementations of `KeyMatcher` to hotkey as well.

Another piece of followup is that more work is needed at the druid-shell level to make consistent `KeyEvent`s for things like control keys - we get ASCII control codes on Windows, the base alpha character on macOS.

**Comment by cmyr** [comment]
I'm going to close this; while we still have work to do, I do not think that the bitwise modifiers are the best approach.
