### ISSUE TITLE
Slack Channel for druid development

### ISSUE THREAD

**Issue by sombrastudios** [xi-editor/druid#372]
Hello, I would really like to be part of some kind of community concerning druid.

I think there is worth in creating a slack channel, right now I'd die to have a little feedback.

Is it possible to create an official Channel / is there an existing Way of communication?

Greetings, Nils Martel

**Comment by cmyr** [comment]
We use Zulip (an open-source slack alternative) for this; feel free to join us at [xi.zulipchat.com](https://xi.zulipchat.com/login/)!

**Comment by sombrastudios** [comment]
Thank you! I'm eager to participate

**Comment by cmyr** [comment]
Looking forward!
