### ISSUE TITLE
Sort Widget methods to represent their lifecycle order

### ISSUE THREAD

**Issue by ul** [xi-editor/druid#377]
It's probably a super-minor issue, sorry was the noise if it is.

When implementing Widget trait for my widgets, I put methods in their lifecycle order (event -> update -> layout -> paint), so it's easier for me to understand how they influence each other.

Also, I decided to give a go CLion with Rust plugin. It has diagnostic which triggers on my impl with the message "Different impl member order from the trait". I guess it's reasonable as having methods in the same order for every impl makes skimming through the code easier.

I wonder if both things sound reasonable and it makes sense to change the order of method declaration in the trait for some gain in ergonomics?

**Comment by raphlinus** [comment]
Yes, I was actually just thinking this as I was preparing the [slides](https://docs.google.com/presentation/d/1fasP_7rIFZtThdigGYZfMz-tMKx8q396v-xS4Gg6DeY/edit?usp=sharing) for my talk. You'll notice that they are in lifecycle order there.

So a PR for this would be quite welcome, should be an easy fix :)

**Comment by Ralith** [comment]
This actually bugged me a bit too.
