### ISSUE TITLE
error: process didn't exit successfully

### ISSUE THREAD

**Issue by Adarma** [xi-editor/druid#395]
Most of the examples don't exit correctly for me on Windows 7 Enteprise SP1 x64.

Many `close gb` messages are printed, but when I close the GUI I have to Ctrl+c to kill the process.

Then I get the following:

    error: process didn't exit successfully: `target\debug\examples\anim.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)

shello and perftest exit correctly.

**Comment by xStrom** [comment]
The problems you are seeing exist for everyone, so you're not doing anything wrong.

The exiting is tracked in #265. The `close gb` issue is tracked in [piet #65](https://github.com/linebender/piet/issues/65).

**Comment by cmyr** [comment]
closing as a dupe, #265 tracks this.
