### ISSUE TITLE
EnvScope doesn't have access to the application state

### ISSUE THREAD

**Issue by s3thi** [xi-editor/druid#415]
The closure that gets passed to `EnvScope::new()` only has access to the application's `Env`. It has no way to access the application's state, which means it's not possible to style widgets based on app state.

For context, I'm building a todo list application in which each todo item is represented by a `CheckBox` and a `Label`. When I click a `CheckBox` to mark a todo as completed, I want the `CheckBox` and `Label` to be rendered in a lighter gray. I can't accomplish this without having access to the application state inside the `EnvWrap` that wraps the `Label` and `CheckBox`.

**Comment by cmyr** [comment]
Interesting, I hadn't really considered this case, and I think it makes sense, especially since `Env` is the only way to really customize the built-in widgets at the moment. I'm curious if we can think more about the underlying thing we're trying to communicate (is there some property of the widget, like 'enabled', that could encapsulate this?) but nothing is coming to me at the moment.

**Comment by s3thi** [comment]
An enabled/disabled state for certain widgets makes total sense. I don't believe Druid currently supports that, but there seems to be a task for this on #143. In my app though, I don't really want to disable anything. I just want to "dim" some widgets depending on app state, which is purely a styling issue.

Maybe it would be useful to be able to bundle common styles in some sort of data structure so they're easier to pass around? That would let me create a `DimmedWidgetStyle` and use it in multiple places. Though I can't tell if that would be better than the current API. I can already create a function called `set_dimmed_widget_env` and pass it to as many `EnvScope`s as I need.

I've generally been thinking about styling in Druid. I typed up a wall of text here but it belongs in a separate issue. See #420.

**Comment by cmyr** [comment]
Very happy to have someone thinking about this area, it's 100% important and necessary and just hasn't been at the top of the list for us, yet, but deserves real care and thought.

I'd thought about something like a 'style collection' but didn't pursue it too far. It's possible that it makes sense, but it isn't totally clear what the API would be. One simple API would be just a wrapper type that takes a reference to a `Theme` and then just gets theme values for different properties? It isn't clear that it would be worth adding an abstraction, but it's certainly possible it could be: I'm a fan of even fairly minor abstractions that improve usability in clear ways.

**Comment by s3thi** [comment]
This week, I'll try sending a PR to make app state accessible from within the `EnvScope` closure, since it seems like we definitely want that.

I'll also keep trying to figure out what a style collection API might look like and write down a proposal for it on a separate topic. I can think of a few use cases for something like that, beyond just being a bit cleaner and ergonomic.

**Comment by cmyr** [comment]
Yea, adding access to data to `EnvScope` is a great first issue, it shouldn't be too tricky. :)
