### ISSUE TITLE
Make mac Window creation smoother

### ISSUE THREAD

**Issue by raphlinus** [xi-editor/druid#43]
As of #42 the window is now "key" when it is created, meaning that it can respond to mouse move events, but on startup from the command line, there are two visual phases with a transition. The first phase shows the window but behind the terminal (at least on my machine), and the second phase pops it to the front. This is not appealing.

For most apps (ie .app bundles) the activation is handled by Launch Services, not by the app binary itself. Colin and I experimented with various things, changing the order of activation, splitting makeKeyAndOrderFront into its two separate components, etc., but weren't able to figure out the Right Way to do this.

This would be a great starter issue for somebody with low level Cocoa knowledge.

**Comment by ratmice** [comment]
I can't test a patch for these not having a mac,
but having been familiar with this a million years ago in the *step days,
my best guess would be to check the level via window.level()
https://github.com/servo/core-foundation-rs/blob/master/cocoa/src/appkit.rs#L981-L982

The other window perhaps has a higher level, this would match the description here:
https://developer.apple.com/documentation/appkit/nswindow/1419444-orderfrontregardless

I imagine the window level should be 4,
https://developer.apple.com/documentation/appkit/nswindow/level/1419265-normal

I don't see the appkit.rs setting it anywhere, so unless it's set implicitly in initWithContentRect...
perhaps it isn't getting set, leading it to order in underneath other windows.

hope that helps.
