### ISSUE TITLE
Process does not exit when window is closed on Windows

### ISSUE THREAD

**Issue by Zwo1in** [xi-editor/druid#438]
As in title, I've runned hello world and layout example. In both the process keep running after window is closed and I need to interrupt it in order to exit.
This is the toolchain I use:
```
stable-i686-pc-windows-msvc
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by raphlinus** [comment]
This is being tracked as #265. It's slightly tricky because the conventions are platform-specific, but we do plan to fix it as it's certainly annoying.
