### ISSUE TITLE
Short Syntax for using Wrapping lenses

### ISSUE THREAD

**Issue by nilsmartel** [xi-editor/druid#453]
I think using LensWraps would be the perfekt moment, for a Shorthand Method.

One could shorten this
```rust
LensWrap::new(WidgetThatExpectsf64::new(), lens!(AppState, value));
``` 

with this here.

```rust
WidgetThatExpectsf64::new().wrap(lens!(AppState, value));
```

Reason I suggest this petty note:

1.) IMO this drastically improves readability
2.) I've jumped back in forth with my cursor when using lenses. I frankly believe this would increase developer satisfaction
3.) Lenses are one of the most important core concepts at play in any non-trivial ui. Giving Devs a good way to use them might result in much appreciation for `druid`

**Comment by nilsmartel** [comment]
If you consider this useful, I'd gladly to create the PR

**Comment by cmyr** [comment]
This kind of maybe exists, in `WidgetExt`, as [the `lens()` method](https://github.com/xi-editor/druid/blob/master/druid/src/widget/widget_ext.rs#L123). Also not documented very well is the stuff you get with `derive(Lens)`; in particular you don't need the `lens!` macro for simple field lenses, you can instead write:

```rust
#[derive(Clone, Debug, Data, Lens)]
struct MyState {
    count: usize,
    scale: f64,
}


fn my_stepper() -> impl Widget<MyState> {
    // Stepper is a `Widget<f64>`.
    Stepper::new().lens(MyState::scale)
}
```

honestly I think what's really missing here is clearer docs in the `lens` module, and I would be very happy for a PR that highlights these two features, in that file?

**Comment by nilsmartel** [comment]
I missed this method, it is precisely what I've wished to have.
Thank you for creating this example.
I think including your Code Sample in the Docs might be a good first step

**Comment by nilsmartel** [comment]
I tried to up my Doc-Comment Game (as I rarely made them in rust, this was a capital opportunity) and created a PR. I also included a small Example of lens usage.
