### ISSUE TITLE
Schedule new event/update pass after paint if commands are queued

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#455]
breaking out of #448. There's currently an issue where commands issued during or after `update` won't be handled until after the next normal event arrives. We shouldn't have to wait; if there are commands to handle, we should immediately schedule a new update, and handle them.

@edwin0cheng you're welcome to take this if you're interested!

> The best way to handle this right now would be to schedule an idle call with the runloop if there are commands to process after painting is finished, that would trigger a new event/update pass.
> 
> This is something we will need to do anyway, because `lifecycle` will work like `update` and you will be able to submit commands there, but we won't run them until after this paint cycle.
> 
> If you're interested in implementing this, you would be welcome to; it would work like `timer` does, where you request a callback from the `WindowHandle` or `WinCtx`, and then I would probably add a `fn idle(&mut self)` method to `druid-shell::WinHandler`, with an implementation in `druid::win_handler` that just processes commands?
> 
> Also the mechanism for scheduling idle tasks exists, but is a bit confusing: basically you call `WindowHandle::get_idle_handle()`, which returns an `Option<IdleHandle>`; then you call `add_idle` on that, passing a closure that will be called with an `&dyn Any` that is actually your `WindowHandler` type; you can downcast that to the correct concrete type and do stuff with it.
> 
> I'm not totally sure what the rationale for this approach is; the basic idea is that you can do arbitrary things with your `WindowHandler` in that closure, like create and dispatch events, but it's definitely an awkward API.
> 

_Originally posted by @cmyr in https://github.com/xi-editor/druid/pull/448#issuecomment-573147934_

**Comment by edwin0cheng** [comment]
> @edwin0cheng you're welcome to take this if you're interested!

Yeah, I would like to take this task, would try to ask more question in Zulip too :)

**Comment by edwin0cheng** [comment]
Although I didn't test it , but I think  it can be closed by #467.
