### ISSUE TITLE
Canvas Component

### ISSUE THREAD

**Issue by Michael-F-Bryan** [xi-editor/druid#459]
Is there some sort of `Canvas` component which gives users access to a `piet::RenderContext`? 

I'm working on a demo for my [`arcs`](https://github.com/Michael-F-Bryan/arcs) project and was wondering if it'd be feasible to write it as a native GUI application using druid.

**Comment by Michael-F-Bryan** [comment]
Lol, ignore me. Looking deeper at the `Widget` trait the `paint()` method gets a `piet_common::Piet`, which will be resolved to the correct `RenderContext` for the current platform.

I'm guessing I'll need to do some coordinate transforms to make sure things are drawn at the correct location (i.e. we want the "origin" to be drawn at the top-left corner of our component, not the window), but that's not too difficult.

**Comment by mendelt** [comment]
Yes, just creating your own custom widget is probably what you want to do here. I believe the parent of your custom widget will already take care of the transformations and offset calculations for you. You could look at the Flex widget to see how positioning and painting of child widgets is done.
