### ISSUE TITLE
Add a title to the window in all examples

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#474]
A bunch of examples currently show the text "app-name" in the title bar. This is unnecessary; you can set a custom title for a window when you create the window description. For an example of what this looks like, see https://github.com/xi-editor/druid/blob/master/druid/examples/identity.rs#L141.

All examples should have reasonable names for their windows; exactly what those names are is an exercise for the implementor?

**Comment by Malmz** [comment]
I could work on this

**Comment by cmyr** [comment]
@Malmz all yours!

**Comment by Malmz** [comment]
Interestingly the gtk backend doesn't actually set the window title. Gonna send a pr soon

**Comment by cmyr** [comment]
closed in #488
