### ISSUE TITLE
Scroll widget gets hot status when scrollbar fades

### ISSUE THREAD

**Issue by Malmz** [xi-editor/druid#493]
In the list example, if you hover over one of the lists scrollbar and then move over to the other one before it fades, both lists will have hot status and compete for scroll events.

![Screencast from 2020-01-29 12_56_52](https://user-images.githubusercontent.com/1337808/73355527-9fb31f80-4298-11ea-80ba-38da0a883e5e.gif)

**Comment by cmyr** [comment]
I think I've maybe seen an issue for this? I haven't looked into it, but I remember raph mentioning something about it at some point.
