### ISSUE TITLE
associate timers with widget ids

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#494]
currently we route timers to all widgets that have ever requested a timer; we can now store the id of the requesting widget along with the timer, and route things that way.

If someone is interested in taking this, it shouldn't be too tricky, and it will be a nice excuse to explore some of druid's internals.

**Comment by sjoshid** [comment]
I would like to take this up if it's ok.

**Comment by cmyr** [comment]
@sjoshid definitely!

**Comment by sjoshid** [comment]
@cmyr 
The timer event is received by all widgets but is acted upon only by the widget that requested it. 

Is the task here to bypass all the traversing so the root widget can directly send the event to the target widget?

**Comment by cmyr** [comment]
sort of! we don't send things "directly"; we still need to traverse the tree, but skip looking at parts of the tree that don't contain the relevant widget. You should be able to get a sense for this by looking at how the 'focus changed' lifecycle event works.

**Comment by sjoshid** [comment]
I traced focus changed event and how it traverses. It is same as timer event. 
* Breadth first search. 
* Traverse children only if target can be reached. (Bloom filters here?). Otherwise move on to next sibling. 

Am I missing something obvious?

**Comment by cmyr** [comment]
sounds about right. All the logic should be in `WidgetPod::event`.
