### ISSUE TITLE
Add a 'Color' type

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#50]
This could even just be a newtype around u32 for now, but we will need one eventually and it makes sense to put something in place now.

**Comment by raphlinus** [comment]
I think this is already tracked in https://github.com/linebender/piet/issues/40 .

I definitely see that I was oversimplifying when I used u32 for rgba 8 bit in piet. You can get away with it for a text editor, but we're going into a new world of hdr, and hardcoding color as u32 will shortly be seen as primitive. But we can have a low-noise conversion, or maybe actually an into, and it will be just as good and a lot more principled.

**Comment by raphlinus** [comment]
Fixed as of https://github.com/linebender/piet/pull/48
