### ISSUE TITLE
expose text measurement during layout phase

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#52]
Currently text measurement is only possible once a handle to the `RenderCtx` is available, which is only in the `paint` fn. To do layout correctly, we need to be able to measure text in the `layout` fn. Not sure exactly how this should be plumbed, but it is currently preventing us from properly implementing most text-focused widgets.

**Comment by SimonSapin** [comment]
Would https://github.com/linebender/piet/issues/47 affect this?

**Comment by raphlinus** [comment]
Yes, these overlap. We need some Rust type other than a piet `RenderCtx` that's capable of doing text layout. Ideally you'd be able to take the text layout object from that and draw it in a `RenderCtx`. As in piet#47, we need to figure out what operations this is capable of. We also need to figure out whether this should simply be part of piet, or split out into a separate crate, as it's not hard to imagine there's value in doing text formatting without it being tied to piet drawing.

**Comment by raphlinus** [comment]
Close this? There are a whole bunch of text improvements in the pipeline, but I think the core issue here has been addressed.
