### ISSUE TITLE
Widget mutators require "self", unable to call in update(&mut self)

### ISSUE THREAD

**Issue by domohawk** [xi-editor/druid#523]
Hi,

I created a widget that wraps a Label I would like to change the background of inside of update(), however the Container mutators all require "self".

Is the proper solution to just add "set_*(&mut self..." variants?

It seems widgets in general heavily use the self/builder pattern, so I am guessing there are other properties that would be useful to be able to mutate under update(), perhaps there is a cleaner way? Is changing update() to take self (and return it) a terrible idea (I am new to Rust)?

Good crate by the way. Thanks!

**Comment by cmyr** [comment]
Ah I understand what's going on I think? (that took me a while).

The methods like `background` are builder-style methods, that are only intended to be used when constructing a widget; they are not for mutating.

One option you have is to rebuild the label widget as required;

```rust
fn update(&mut self, ctx: &mut UpdateCtx, old: &T, new: &T) {
    if !old.same(&new) {
        let new_color = self.color_for_data(new);
        self.label  = Label::new("my text").background(new_color);
        ctx.children_changed();
    }
}
```

An approach that might be nice is if a `Container` could take a theme key as its background color, and then you would just need to change that theme item in order for the background to have its color changed; this would be less heavy weight.

**Comment by domohawk** [comment]
Rebuilding works, but might be a performance concern if the rebuild is expensive, which is maybe not a concern for Label but maybe for more complex widgets.

It also requires I move all the Label layout logic into my wrapper, which may not be a bad thing, but does separate the layout from the root build_widget().

My use case was to have a list of labels where one is "selected", using background color as a dynamic property. Current wrapper:
```
// Label widget wrapper for dynamic properties
struct DynamicLabel {
    label: Container<ListItem>,
}

impl Widget<ListItem> for DynamicLabel {
    fn event(&mut self, ctx: &mut EventCtx, event: &Event, data: &mut ListItem, env: &Env) {
        self.label.event(ctx, event, data, env);
    }

    fn update(&mut self, ctx: &mut UpdateCtx, old_data: Option<&ListItem>, data: &ListItem, env: &Env) {
        self.label.update(ctx, old_data, data, env);
        if data.is_selected {
            self.label.set_bg(Color::rgb(0.7, 0.2, 0.2));  // Added to Container
        } else {
            self.label.set_bg(Color::rgb(0.5, 0.5, 0.5));
        }
    }

    fn layout(&mut self, layout_ctx: &mut LayoutCtx, bc: &BoxConstraints, data: &ListItem, env: &Env) -> Size {
        return self.label.layout(layout_ctx, bc, data, env);
    }

    fn paint(&mut self, paint_ctx: &mut PaintCtx, data: &ListItem, env: &Env) {
        self.label.paint(paint_ctx, data, env);
    }
}
```

This lets me build the Label only once and keep all the layout/styling together (though maybe this isn't a good idea for larger projects?)

```
let mut row = Flex::row();
    row.add_child(
        Scroll::new(
            List::new(|| {
                DynamicLabel {
                    label: Label::new( | item: &ListItem, _env: &_ |
                    format!("List item: {}", item.value))
                    .padding(10.0)
                    .expand()
                    .fix_height(50.0)
                    .background(Color::rgb(0.5, 0.5, 0.5))
            }
        })
        ).vertical().lens(DataModel::ls), 1.0);
```

But it sounds like it was intentional that properties like background() are not dynamic? In general it seems that current Widget system are designed so that the only "dynamic" content is in their type parameter, but there are lots of other properties of Widgets that seem useful to be dynamic (layout, styling, etc). Is rebuilding widgets the desired approach to change these properties?

**Comment by cmyr** [comment]
The easiest thing for you to do is to not use container, and just paint the background as you desire in your `DynamicLabel`'s paint method.

Thinking about this more, though, there really isn't any reason that you shouldn't be able to change a Container's attributes at runtime, it just isn't something we'd thought of yet. Certainly changing the `background` should be fine; if you change the border you would have to be careful to make sure you invalidated, because it will change the layout.

The ideal, canonical way of doing this (which isn't possible, but would be if we implement #526) is to have the color for the button be specified as a variable in the `Env`, and then use an `EnvScope` widget to set the color based on the state.

This would look something like,


```rust
const DYN_LABEL_BACKGROUND: Key<Color> = Key::new("my-unique-key.for-my-label");

let dyn_label = Label::new("my text")
    .background(DYN_LABEL_BACKGROUND)
    .env_scope(|env, data| {
        let color = data.color_for_this_label();
        env.set(DYN_LABEL_BACKGROUND, color);
    });
```
