### ISSUE TITLE
No way to get the visible size of the widget when the Size is infinite

### ISSUE THREAD

**Issue by jjl** [xi-editor/druid#535]
It looks like the Region (from PaintCtx) might be a way to do this, except the Rect it contains is currently private.

Have I missed something?

**Comment by cmyr** [comment]
Does `PaintCtx::size()` do what you need?

**Comment by jjl** [comment]
This is in the case that size is infinite, e.g. inside a Scroll Widget

**Comment by jjl** [comment]
I had a little think about this, and because this is during *painting* (i.e. after layout), I think PaintCtx.size() should return the visible size (which would by definition not be infinite). Whether this is a bug in Scroll or something else, I'm not sure.

**Comment by cmyr** [comment]
`PaintCtx::size()` returns the size of the widget, and does not account for what is visible on screen. 

Inside a scrollview your constraints are infinite (you can be infinitely large) but you are still expected to return a concrete, non-infinite size? This isn't enforced, but things certainly get weird if you don't.

**Comment by jjl** [comment]
Ah, I see. My widget just calls max() on the box constraints it is given during layout right now, as I haven't hooked it up to measure everything properly.

My widget is a terminal emulator, so I need to figure out how many rows/columns it maps to. Do you have a recommended way of getting this information?

**Comment by cmyr** [comment]
I don't have any clever solution; you'll need to figure out what your font is, and then from there get your height and advance/width. Assuming you are using a fixed width/pitch font this could be as easy as creating a layout for any single 'single width' character, and measuring that.

**Comment by jjl** [comment]
Indeed, the project was picked specifically because we normally use monospace fonts with terminals and so it's more amenable to being doable with cairo's toy text rendering.

However, while I can measure what the print width will be, I still need a way to determine the visible width. Would resize events be the way to go for that?

**Comment by cmyr** [comment]
oh, I think I understand. Yes, currently size of the window is delivered to the root widget via `Event::Size`. It will also be provided to the root widget during layout.

**Comment by jjl** [comment]
Great, thanks!
