### ISSUE TITLE
Cannot set a timer when handling WinHandler::connect (windows)

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#548]
At the point where the windows backend calls `WinHandler::connect`, the window has not been fully instantiated(?). Timers requested during this event (`Event::WindowConnected` in druid) never fire.

Noticed this because the `identity` example doesn't work correctly on windows.

**Comment by raphlinus** [comment]
This might be related to #533, which changed the order of window creation. In any case, I agree this is a good thing for people to investigate.
