### ISSUE TITLE
Examples fail on Win7x64

### ISSUE THREAD

**Issue by Adarma** [xi-editor/druid#555]
Has support for Windows 7 been dropped?

I know it is dead, but I'm still on Win7x64 on a work machine.

With 19e4e0e35b27d76b3e895b6c23ec2928f3fa966c, I get the following error when running `cargo run --example calc`:

> DEBUG [druid::localization] available locales [], current en-US
> DEBUG [druid::localization] resolved: [en-US]
> ERROR [druid_shell::platform::windows::util] No shcore.dll
> ERROR [druid_shell::platform::windows::util] Could not load `GetDpiForSystem`. Windows 10 or later is needed
> ERROR [druid_shell::platform::windows::util] Could not load `CreateDXGIFactory2`. Windows 8.1 or later is needed
> thread 'main' panicked at 'launch failed: Platform(NullHwnd)', src\libcore\result.rs:1188:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> error: process didn't exit successfully: `target\debug\examples\calc.exe` (exit code: 101)

**Comment by raphlinus** [comment]
This was broken by #551, which was intended to be a refactor that didn't change compatibility. I haven't dug into exactly what's going wrong.

The warnings about 8.1 and 10 are optional features and probably shouldn't be spammed to the log at all, they're perfectly normal when running on 7.

**Comment by cmyr** [comment]
I see one possible problem: `Application::init()` is being called from `Application::run()` and it should really be at `Application::new()`. I don't have a win7 machine to test on, but this would be my first guess.
