### ISSUE TITLE
Either doesn't resize it's 'off' branch on gtk

### ISSUE THREAD

**Issue by Giesch** [xi-editor/druid#560]
IE, an on/off toggle button doesn't resize its off widget when you resize the window while it's on, and it doesn't resize the on button if you resize the window while it's off. When you flip back, the other state will have preserved its original size.

It looks like a simple fix might be to have Either::layout always do both sets of work, and then return the appropriate size. If that's good enough, I can make a PR.

Edit: I just saw there's a request_layout on ctx. I guess it should just do that in update right before request_paint? (and not do extra work all the time)

**Comment by Giesch** [comment]
It looks like ViewSwitcher doesn't have this problem, and the thread on that PR also has [some info](https://github.com/xi-editor/druid/pull/507#discussion_r375925444) for how to fix this in a not awful way.

**Comment by cmyr** [comment]
Yes, I think `request_layout` in update if thee widget has changed is the most elegant solution. Would be happy to accept a patch for that!

We used to always do layout all the  time, but that changed recently (#528, which also introduced `request_layout`) and so it is reasonable that some little bugs like this are surfacing as a result.
