### ISSUE TITLE
Lens derive fails if method exists with same name as member

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#563]
e.g.

```rust
#[derive(Lens)]
struct Boots {
    leather: bool,
}

impl Boots {
    fn leather(&self) -> bool {
        self.leather
    }
}
```

will produce the cryptic error,

```
error[E0592]: duplicate definitions with name `leather`
  --> src/your_file.rs:N:N+M
   |
20 |   #[derive(Lens)]
   |            ---- other definition for `leather`
...
26 | /     fn leather(&self) -> bool {
27 | |         self.leather
28 | |     }
   | |_____^ duplicate definitions for `leather`
```

I think the _best_ solution here is to have something like a `#[druid(lens_name = "leather_lens")]` annotation that can be added to the field, and then to print a message suggesting that.

I think the _easier_ solution would be to just keep appending underscores until we find a valid identifier 😬.

**Comment by emigr2k1** [comment]
Shouldn't this be closed?

**Comment by cmyr** [comment]
Thanks!
