### ISSUE TITLE
Error running image example

### ISSUE THREAD

**Issue by Adarma** [xi-editor/druid#566]
Was interested to try the new image widget, but when I try to run the example I get the error:

```
$ cargo run --example image --features "images"
error: --features is not allowed in the root of a virtual workspace
```

Am I missing something, or is it a cargo or druid issue?

> stable-x86_64-pc-windows-msvc 
> rustc 1.41.0

**Comment by Adarma** [comment]
Running from druid\druid, I get:

`error: Package `druid v0.5.0 (C:\CODE\Rust\druid\druid)` does not have these features: `images``

**Comment by cmyr** [comment]
oops, the feature name is `image`.

**Comment by fishrockz** [comment]
@Adarma this looks like a issue from a older version of my PR. I thought the version that got merged to master had fixed this.

I don't have easy access to windows + rust so i cant test if @cmyr 's patch fixes this.

**Comment by cmyr** [comment]
oh yea I was confused, this maybe is an old commit? I didn't notice when doing #567 that I didn't actually end up needing to change the feature name, so maybe this is just on an old commit?

**Comment by Adarma** [comment]
Running from druid\druid with current master branch, 9aabfc25b2226ff546a4e2c796c5ea387fea68d6 is working.

**Comment by Adarma** [comment]
I'm a bit confused too! I'm sure I got the message to use the "images" feature, but can't find it in the commit history.

**Comment by fishrockz** [comment]
Ah, so, I "Fixed up" the "same" commit as @cmyr and others gave me feed back you can see this in the PR notes ( https://github.com/xi-editor/druid/pull/557 ), one of the old versions that got "Fixed up" https://github.com/xi-editor/druid/commit/cff6224be9044a228a4d3531bec7354521aab9d3 has the offending message.

You might be able to find the old commit with `git reflog` but the current branch of fishrockz:willsalmon/images nor master point to the old commit.

I was in effect making a change then running `git commit -a --amend` then `git push fishrockz willsalmon/images -f`each time i got feed back from Colin

**Comment by cmyr** [comment]
Great, happy to have this resolved. :)
