### ISSUE TITLE
Fullscreen?

### ISSUE THREAD

**Issue by MGlolenstine** [xi-editor/druid#574]
I'm running druid on an embedded device and it's working perfectly well. Now I was just wondering, if there was a way to make it occupy whole screen and remove the title bar?

**Comment by cmyr** [comment]
This requires a bit of work; #427 is probably the best tracking issue. Depending on your platform this may work already, for instance macOS lets all windows participate in full-screen by default, but other platforms will require exposing various window customization options in `druid-shell` and then exposing this via druid.

Where are you running?

**Comment by MGlolenstine** [comment]
I'm currently running it in an embedded environment on Linux/GTK.
I figured out, that by disabling the LXDE and forcing OpenBox to display everything fullscreen, the app does become fullscreen, but the title bar is still present (which you can't remove because of windows... or something similar I read about few hours ago...)
