### ISSUE TITLE
Multiple list scrolling

### ISSUE THREAD

**Issue by MGlolenstine** [xi-editor/druid#575]
I found a "bug" with the code within the `list.rs` example. I'm saying "bug" in quotes because I'm not sure if this is intentional or not, but whenever both lists overflow the window, upon scrolling one of them, both of them scroll... But not always, it just seems random.

**Comment by ForLoveOfCats** [comment]
I cannot reproduce on Linux/GTK. When you say overflow do you mean vertically or something else? What platform are you on?

**Comment by MGlolenstine** [comment]
@ForLoveOfCats Correct! I meant the vertical, the overflow that happens after you click the "Add" button a few times.

I'm on Arch Linux with GTK

**Comment by ForLoveOfCats** [comment]
I have noticed another bug with the scrollbars but I still cannot reproduce the issue on master (currently a5018a1d08948249f861fd62754d2adaf9f8e86c)

**Comment by MGlolenstine** [comment]
I'm currently using the `druid` crate from the `crates.io`, but I'll try the master, maybe it was fixed in-between the versions.

**Comment by MGlolenstine** [comment]
I can also confirm that the same problem("bug") happens on an armhf build for linux/X11 with GTK

**Comment by MGlolenstine** [comment]
Ok, `master` branch fixed it!

Thanks for the help @ForLoveOfCats !

**Comment by cmyr** [comment]
yea this was fixed recently. Thanks for the issue, though! Also I would definitely be using master right now, there have been a bunch of significant changes.
