### ISSUE TITLE
Scroll not getting mouse events for scrollbars outside Scroll bounds

### ISSUE THREAD

**Issue by ForLoveOfCats** [xi-editor/druid#576]
When dragging a scrollbar on a Scroll if the mouse leaves the Scroll bounds then it no longer receives mouse events. This causes the scrollbar to not update its position based on mouse movement and a mouse up event will not be registered by the Scroll so the scrollbar will still be in the dragging state once the mouse re-enters the Scroll bounds. This is basically https://github.com/xi-editor/druid/issues/457 but between widgets. When a widget has the mouse held atop it the mouse events should continue to be sent to it even outside its paint bounds.

**Comment by cmyr** [comment]
yep agree this is a bug, haven't looked into it but scroll should be set as active and should continue to receive events even when the mouse is in another widget.

It might be that scroll is receiving the event, but we're then failing some check in the event handling code? but just an idea...

**Comment by ForLoveOfCats** [comment]
Ah I see, so the plumbing for this is already present. Scroll is simply either not using it or using incorrectly?

**Comment by cmyr** [comment]
yea, that is my understanding. Widgets can capture the mouse (or more accurately, register to receive all mouse events) by making themselves 'active' while handling an event.
