### ISSUE TITLE
STATUS_ACCESS_VIOLATION in examples

### ISSUE THREAD

**Issue by TannerRogalsky** [xi-editor/druid#593]
When I press enter/return on my keyboard in the context of a text box, the application crashes.

I can replicate this every time in both the "switch" and "textbox" demos on Windows 10.

**Comment by raphlinus** [comment]
This is https://github.com/linebender/piet/pull/126. All we need to do is make another piet release.

**Comment by Dmitry-Borodin** [comment]
@TannerRogalsky piet was updated since than, Could you check if issue is still there for current master?

**Comment by Zarenor** [comment]
I've just tested a couple of the examples with textboxes ('switch' and 'styled_text'), and the issue seems resolved. Marking as closed for now. Please let us know/reopen if you still see the issue.
