### ISSUE TITLE
allow setting minimum window size

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#632]
This will be very similar in implementation to #587.

**Comment by Finnerale** [comment]
I've implemented it but I'm (again) not sure about naming :sweat_smile: 

The function to set a windows initial size is called `WindowDesc::window_size` thus is would be consistent to call the function for minimal size `window_min_size` but it seems odd to me when another function is called `WindowDesc::title` and not `window_title`.

Also based on the discussion in #697 it would make most sense to call it `with_min_size` and `with_title`.

Thus I would call the function `WindowDesc::with_min_size` in my PR and then make another one to rename all other methods of `WindowDesc` to builder style naming

**Comment by cmyr** [comment]
yea, naming is a disaster.

something like `WindowDesc` is _only_ a builder, so I don't feel too bad about not using `with` everywhere. That's mostly a problem with widgets. I would be happy with either `min_size` or  `with_min_size`.

**Comment by cmyr** [comment]
This is now added in druid, but we still need druid-shell support for mac & windows.

**Comment by xStrom** [comment]
This was implemented for Windows by #727. There's also a macOS specific issue for this at #714.

**Comment by cmyr** [comment]
okay, lets close in favour of #714
