### ISSUE TITLE
implement window resize option

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#633]
This was implemented for gtk in #587, but still needs to be implemented for mac and  windows.

These can be done separately, that is if someone wants to do mac but not windows that's fine!

**Comment by emigr2k1** [comment]
I think this should be closed

**Comment by xStrom** [comment]
It's [not implemented](https://github.com/xi-editor/druid/blob/267e06870894bff78d9cd60ab5966f070b2007d3/druid-shell/src/platform/mac/window.rs#L692-L693) on macOS yet.

**Comment by emigr2k1** [comment]
My bad. I thought that this issue was about the resizable option in `WindowDesc` that already works.

**Comment by totsteps** [comment]
I think this can be closed as it was implemented in #773 at [code](https://github.com/xi-editor/druid/blob/3b3d7a00b44824fae98cf48390e948e5d73a6329/druid-shell/src/platform/mac/window.rs#L698).

**Comment by cmyr** [comment]
yep thanks!
