### ISSUE TITLE
cannot derive Data within druid module

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#650]
This is one of those macro gotchas. There's some trick to make this work consistently, which I'm sure david tolnay has an example of somewhere. 😁

**Comment by kindlychung** [comment]
And `Lens` also? 
I ran into this while trying to derive `Lens` for `ImageData`. The derive macro is using something like `druid::lens::Lens`, while inside druid, it's expecting `crate::lens::Lens`.

I hope the fix will be merged soon. :)
