### ISSUE TITLE
How can I exit an app if closed window?

### ISSUE THREAD

**Issue by usagi** [xi-editor/druid#674]
Expected behavor:

![image](https://user-images.githubusercontent.com/115972/76730667-12bc1b00-679f-11ea-90c6-1664179f9b0e.png)

Actual behavor:

![image](https://user-images.githubusercontent.com/115972/76730921-95dd7100-679f-11ea-95cd-c7b12d944e40.png)

In the other words, how can I exit the `AppLauncher`'s loop?

```rs
  AppLauncher::with_window(window).use_simple_logger().launch(calc_state).expect("launch failed");
```

**Comment by xStrom** [comment]
This is a known issue tracked in #265. Right now the solution is to Ctrl+C the console app.

**Comment by cmyr** [comment]
indeed, this is a pretty easy fix if someone is interested, but I'm not going to get to it for a while.

**Comment by usagi** [comment]
@xStrom Thank you for the guidance on duplication.

@cmyr Okay, I understand your interest. But I and several developers has interested the issue. Thus, I was PRed #681.

**Comment by cmyr** [comment]
@usagi the place to fix this is https://github.com/xi-editor/druid/blob/master/druid/src/win_handler.rs#L223

**Comment by usagi** [comment]
@cmyr Thanks, I'm read around that and implementation of application.rs for each platforms. And try to it:

```
    fn remove_window(&mut self, window_id: WindowId) {
        self.with_delegate(|del, data, env, ctx| del.window_removed(window_id, data, env, ctx));
        // when closing the last window:
        if let Some(mut win) = self.windows.remove(window_id) {
            if self.windows.windows.is_empty() {
                // on mac we need to keep the menu around
                self.root_menu = win.menu.take();
                //FIXME: on windows we need to shutdown the app here?
                Application::quit(); // <-- fixing for the problem!
```

It works and solve the problemfor Windows. And it also works on GTK/Linux without a troubles. But, the method also effect to OSX and I saw your old comments for OSX:

> Yea, thanks for this. It's a slightly tricky one because there are platform-specific expectations; on windows we should kill the application when the main window closes, but on mac we shouldn't.
> 
> There's a separate problem on mac where once the last window is closed the menu stops working. :/

https://github.com/xi-editor/druid/issues/265#issuecomment-550431088

Unfortunately, I have not OSX environment then I cannot fix the issue use the simple method without darty `[cfg(target_of...)]`.

**Comment by giannissc** [comment]
It should be noted that the shello example is closing normally when the button is pressed

**Comment by cmyr** [comment]
What I would recommend is just making this `#[cfg(target_os = "windows")]`. gtk is handling this elsewhere, and mac is not supposed to close when the last window c loses.

**Comment by thecodewarrior** [comment]
It would be great if it was an option for macOS. While most apps don't close when their last window closes, that doesn't mean none of them do. The ones that stay open are generally multi-window apps, and the ones that close are ones where there is only ever the one window. 

If the app has only the single window there's no way to make a new window once you close the main one, so it should just quit the app. I'm not suggesting doing any kind of auto-detection, but having a toggle would be nice.

**Comment by cmyr** [comment]
You as the programmer are free to exit if the last window is closed, but I would generally think of this as an anti-pattern; at the very least I can't think of an example of a 'well behaved' mac app that does this? Maybe things are relaxing as iOS becomes more dominant, I dunno.

**Comment by thecodewarrior** [comment]
After a bit of investigation, I've identified a number of built-in mac apps that quit when their last window closes. They're all apps with only a single window:
- App Store
- Notes
- Reminders
- Contacts
- FaceTime
- Calculator
- Dictionary
- Font Book
- Disk Utility
- Airport Utility

**Comment by cmyr** [comment]
Interesting, I didn't know that. Thanks!
