### ISSUE TITLE
replace all use of paint_ctx with ctx

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#682]
at least when it occurs in the context of a `paint` method. In all other widget methods we call the context `ctx`, and paint stands out for its inconsistency.

**Comment by vishalsodani** [comment]
@cmyr I had a look at this. How should I rename in core.rs?
There is another object created inside paint method with ctx name.

**Comment by cmyr** [comment]
Use your judgement, whatever makes the code easiest to read.

I would be fine if this change was only made within widgets' `paint` methods.
