### ISSUE TITLE
replace Stepper::min/max with 'with_range'

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#684]
I think these two methods are slightly too generally named, and I would like to be consistent with the new method on Slider.

**Comment by Finnerale** [comment]
I've just started to get this done, but renaming it to `with_range` feels kind of weird when the next line is `step(..)` and not `with_step(..)`.
Currently there are many methods not using the builder style naming `with_` and it feels like this change would make the naming less consistent.
I think it would be best to first decide whether to use builder style naming for all of none of the methods. My favorite would be naming it just `range(.., ..)` as the `with_` prefix really only makes sense when there are equivalent none builder methods on the same struct.

**Comment by cmyr** [comment]
yep, `with_step` is also welcome.

My current feeling is that builder-style methods that take an argument should be `with_`. I have two main concerns: one is just consistency, and having a clear convention for naming, and the other is that overly generic method names are likely to collide with other things (for instance, there's a problem with colliding with derived lens names)— but also specifically that with `WidgetExt` if we have overly generic method names and those are auto-impl'd for a bunch of types, it becomes quite likely there will be a collision on some type, which will cause hard to diagnose compiler errors.
