### ISSUE TITLE
why not use amethyst for this?

### ISSUE THREAD

**Issue by unmellow** [xi-editor/druid#7]
was watching [this video](https://www.youtube.com/watch?v=4YTfxresvS8) and was wondering why
you didn't mention [amethyst](https://github.com/amethyst/amethyst) as an option it uses an ECS too 
and even though it's a work in progress as far as I know 
it's closer to completion than this

ps: I'm aware this is not the place to say this but IDK how else to ask this
also this post might seem rude but I don't mean it to

**Comment by raphlinus** [comment]
I'm not sure I was aware of amethyst back when I gave that talk. I agree it's a promising approach. I think the scope is quite a bit more tuned to games and less to general UI.

More documentation is needed explaining the big picture, especially as that continues to evolve. For example, targeting the Web is now an explicit goal, and the new [piet](https://github.com/linebender/piet) crate has web canvas as a back-end co-equal with the other two. I do talk about this a fair amount in a recent [podcast](https://xi-editor.io/updates/xi-day-radio.html).

Last, issues are fine but for more chatty-style questions, please visit the [Zulip chat](https://xi.zulipchat.com), in particular the [#druid stream](https://xi.zulipchat.com/#narrow/stream/147926-druid).

**Comment by unmellow** [comment]
thanks for the answer I'll keep this in mind next time
