### ISSUE TITLE
PSA: breaking changes to the Flex widget

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#708]
I am shortly going to merge #691 and #707, and this is going to change the API and behaviour of the `Flex` widget; by implication it is also going to break most existing druid code. If you are not following master, this will be part of v0.5.0.

## API:

what was previously,

```rust
fn add_child(&mut self, child: impl Into<Widget<T> + 'static, flex: f64) { .. }
```

is now,

```rust
fn add_child(&mut self, child: impl Widget<T> + 'static) { .. }
fn add_flex_child(&mut self, child: Widget<T> + 'static, params: impl Into<FlexParams>) { .. }
```

This forces you to be clear about whether you want a flexible or non-flexible child. `FlexParams` is a type that also allows additional options to be set for a given child; but you can continue to pass a `f64` to this function as was previously the case with `add_child`.

## Behaviour changes:

- Previously, items that had a 'flex factor' were always passed tight constraints; this meant that they were forced to use up all available space. This is no longer true; if you want to force a widget to use its flex space, you have to explicitly expand it, with one of `expand`, `expand_width`, or `expand_height`. (On `SizedBox` or `WidgetExt`.)
- Previously, were always positioned to the top or leading edge of the cross axis; that is, in a row, items would always be aligned to the top of the row. By default, items are now centered on the cross axis; this can be changed by setting an explicit `CrossAxisAlignment`.

If anyone is having any trouble with this, feel free to ask questions here.

**Comment by Finnerale** [comment]
@cmyr Shall we close this?

**Comment by xStrom** [comment]
I think it's safe to close, we've been using the new API for quite some time now.
