### ISSUE TITLE
split `druid` derive attribute into `data` and `lens`

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#723]
Currently we have a single `druid` attribute in our derive macros. Eventually (I suspect) we are going to want more flexibility here, and I think it makes sense to break this up into separate `lens` and `data` attributes, aka

```rust
#[derive(Clone, Data, Lens)]
struct Before {
    #[druid(same_fn = "PartialEq::eq", lens_name = "file_path")]
    path: PathBuf,
}

#[derive(Clone, Data, Lens)]
struct After {
    #[data(same_fn = "PartialEq::eq")]
    #[lens(name = "file_count")]
    path: PathBuf,
}
```

It would also be nice if we still checked for the `druid` attribute and printed a helpful failure message.

This should bump `druid-derive` to the next minor version.

**Comment by Dmitry-Borodin** [comment]
@cmyr I think this can be closed

**Comment by cmyr** [comment]
Thanks!
