### ISSUE TITLE
Configurable label font

### ISSUE THREAD

**Issue by thecodewarrior** [xi-editor/druid#774]
It would be great if labels could have configurable fonts. One of my projects needs labels with monospaced text, but I don't want all the text in the UI to be monospaced. From what I can tell this isn't possible right now since at the moment Label's [`get_layout`](https://github.com/xi-editor/druid/blob/ddafe0dfb8cf6f03a735dc80d853e8c89167710d/druid/src/widget/label.rs#L166-L173) gets the font name from the theme. Probably the most elegant solution would be an `Option<String>` with the theme being used as the default if the font is `None`.

**Comment by cmyr** [comment]
I agree this makes sense, and a PR would be welcome; font should work the same as color and size.

cc @futurepaul who has been thinking about this lately.

**Comment by futurepaul** [comment]
I haven't tried anything out yet but ideally you can follow the example of the builder / setter pair we have for size and color. That way Label::new sets the font as `theme::FONT_NAME` and then the builder or setter updates that value, no need for an option. I'm curious if we can do KeyOrValue here as well, but I haven't used that yet with a String so no guarantees.

**Comment by thecodewarrior** [comment]
`theme::FONT_NAME` is the key for the environment, not the actual font name. If we don't use an `Option` then we either store the env key, meaning we couldn't directly set the font name, or directly store the font name and grab the theme font name once during creation, neither of which are good ideas IMO.
