### ISSUE TITLE
Make text module public? 

### ISSUE THREAD

**Issue by rhzk** [xi-editor/druid#776]
The text module have functions that can be useful when creating custom widgets.
It would be nice to have it as public instead of reimplementing those functions.

Example widget (basically TextBox with added features):
![multiline](https://user-images.githubusercontent.com/45132707/77936059-a1a65880-72b2-11ea-8c63-7fe2d5cc6bd6.gif)

**Comment by cmyr** [comment]
yep, this should be public.
