### ISSUE TITLE
Add druid book to repo info

### ISSUE THREAD

**Issue by tbillington** [xi-editor/druid#800]
Github repos support having a website linked next to the description.
I propose adding https://xi-editor.io/druid/ to the druid repo so people can easily find the book.

Pic of https://github.com/xi-editor/xi-editor utilising this:

![Screen Shot 2020-04-04 at 12 49 21 pm](https://user-images.githubusercontent.com/2771466/78416179-c6b01800-7672-11ea-9959-4530ada20f6b.png)

**Comment by cmyr** [comment]
Good idea, thanks!
