### ISSUE TITLE
How to use with opengl?

### ISSUE THREAD

**Issue by happydpc** [xi-editor/druid#804]
I want to use this ui to show 3d viewer. How can I do this?

**Comment by raphlinus** [comment]
It's out of scope for now. I definitely appreciate the interest in this, but it's a hard problem and would need someone with a fairly deep understanding of gpu integration.

My personal feeling is that wgpu is the way forward, not OpenGL, but there are tradeoffs here as well.

**Comment by Finnerale** [comment]
I suppose this can be closed for now, I've opened #806 to define the scope of this project so that people can see whether druid fits their project.
