### ISSUE TITLE
Replace `#[macro_use]` with normal `use`

### ISSUE THREAD

**Issue by Finnerale** [xi-editor/druid#805]
[druid-shell/src/lib.rs#L27](https://github.com/xi-editor/druid/blob/a8d062a919868d7dca5aac885dfec9dc99f1a313/druid-shell/src/lib.rs#L27)
```rust
#[cfg(target_os = "windows")]
#[macro_use]
extern crate winapi;

#[cfg(all(target_os = "macos", not(feature = "use_gtk")))]
#[macro_use]
extern crate objc;

#[cfg(not(any(feature = "use_gtk", target_os = "linux")))]
#[macro_use]
extern crate lazy_static;

#[cfg(all(target_os = "linux", feature = "x11"))]
#[macro_use]
extern crate lazy_static;
```
This is no longer necessary with Rust2018 and should be replaced with use statements in modules that actually utilize those macros

**Comment by totsteps** [comment]
@Finnerale would love to fix this.
I am a beginner with rust, can you point me what needs to be changed and how.

Thanks.
