### ISSUE TITLE
Add `WidgetPod` to `widget::prelude`

### ISSUE THREAD

**Issue by Finnerale** [xi-editor/druid#809]
Considering [this comment](https://github.com/xi-editor/druid/pull/751#discussion_r397872537) by @cmyr 

>Basically: for a widget to fully participate in druid (to have an id, to have its own hot state, to be focusable, to correctly handle events) that widget needs to be in a WidgetPod. One way of thinking about WidgetPod is that it is the 'base class' for a widget.

It seems like whenever a widget contains other widgets they need to be wrapped into a `WidgetPod`, thus it would seem useful in the `widget::prelude`.

Currently  `widget::prelude` contains only items that are *required* when writing a widget while `WidgetPod` would only be necessary for 'meta widgets' such as layouts, toolbars etc.
I think however that there are enough of such widgets to warrant the inclusion of `WidgetPod`

**Comment by xStrom** [comment]
I think this is a good idea and indeed we should increase our promoting of the importance of `WidgetPod`. It does more and more heavy lifting and having child widgets without `WidgetPod` is looking like an increasingly niche situation which should probably be reserved for performance optimizations in special cases.

**Comment by cmyr** [comment]
I'm not opposed. The original qualification I used for whether something was in the prelude was whether or not it appeared in the signature of a method on the `Widget` trait, and `WidgetPod` does not; however that was an arbitrary choice.

There are certainly *lots* of things you will need to import to implement various bits of widget functionality; for instance you can't handle keyboard events without some of `KeyEvent`, `KeyCode`, `HotKey`, etc; so it isn't sure exactly where the line should be. 🤷‍♀

**Comment by xStrom** [comment]
It's true, the signature requirement is a pretty natural line.

Perhaps it makes sense to make another prelude with some other collection of common stuff? So `WidgetPod` but perhaps also `Data` and maybe some lens stuff? I'm not sure what a good list would be, but there's probably a few of these things that are rather common but not strictly needed for the signature.

**Comment by cmyr** [comment]
I tried this a while ago and it just wasn't clear where the line was. I don't love glob imports in general. If someone has a concrete suggestion I'm open to that, but I don't have any good ideas myself.

**Comment by xStrom** [comment]
Yeah I'm leaning back towards the *stuff to implement `Widget`* hard line. It's super straightforward and useful.

Also when thinking about potential renames like `WidgetPod` to `Widget` and `Widget` to say `Component` or something, then having `Widget` (WidgetPod) in the `Component` prelude feels less right.

**Comment by Finnerale** [comment]
> when thinking about potential renames like `WidgetPod` to `Widget` and `Widget` to say `Component` or something

I like that thought :+1: 

> the stuff to implement Widget hard line.

And any widget that contains another *requires* `WidgetPod` and in order to use it `Data`.

So I think this is basically about if the prelude should contain
- what's necessary for most widgets
- or only items from `Widget`s signature

I just noticed that `WidgetId` is included in the prelude but not in any signature of `Widget` :thinking:

**Comment by cmyr** [comment]
It is in the signature of a `#[doc(hidden)]` widget method.

The prelude in the widget module is intended very specifically to cover all the types *required* in order to implement `Widget`. `WidgetPod` doesn't cut it. The only thing that is *minorly* borderline is the `RenderContext` trait, which is not strictly required but is the source of most of the methods on `PaintCtx`.

The idea is basically that you should be able to copy the widget trait, import the prelude, and compile. Whatever specific things you need, you can import.

I just can't think of any other clear principal for what does and doesn't make it. I need `Color` more often than I need `WidgetPod`, but it is not in the prelude. nor is `Rect`.

**Comment by Finnerale** [comment]
> It is in the signature of a #[doc(hidden)] widget method.

I see, but considering you are not supposed to override that anyways I don't think `WidgetId` should be in the prelude but then again that probably doesn't really matter.

> The only thing that is minorly borderline is the RenderContext trait

Missing traits are kind of annoying so I'm happy it's in there.

> I just can't think of any other clear principal for what does and doesn't make it.

Considering that I don't fare any better at this I'll close this issue for now.
