### ISSUE TITLE
Question: Panel with two rounded corners, not four?

### ISSUE THREAD

**Issue by nuxeh** [xi-editor/druid#844]
Hi,

I was just wondering if i could round the corners of a panel but only selected corners, keeping the others square.

I notice that most of the rounded calls call back to piet's rounded corners type, which doesn't seem to support this. I'm just curious if there's an easy way to achieve this that i'm not aware of.

I'm just starting to use druid, but very much liking what i've seen so far!

**Comment by xStrom** [comment]
No easy way right now, however you can use `clip` to achieve this. Make a rect with four rounded corners and then cut one edge off with `clip`.

**Comment by nuxeh** [comment]
Great, thanks! That's perfect.
