### ISSUE TITLE
Little bug in `Switch`

### ISSUE THREAD

**Issue by derekdreery** [xi-editor/druid#864]
When you mouse-up a switch, it will always switch even if you didn't mouse down on it. So if you mouse down on one switch, move to another, and mouse up, then they will both change.

I think the fix would be to do an `is_active` check in the MouseUp event handler, but I haven't looked.

**Comment by derekdreery** [comment]
Only seems to be in master - not in the 0.5 published crate.

**Comment by xStrom** [comment]
Any widget that does its behavior on `MouseUp` should make sure it first received `MouseDown` to "arm" it. I haven't looked but wouldn't be surprised if this issue goes beyond just `Switch`.
