### ISSUE TITLE
Embedding Xi as a featurefull text editor widget

### ISSUE THREAD

**Issue by davidrusu** [xi-editor/druid#871]
For a quick and dirty experiment, I wanted to have a fully featured text-editor in a druid application and it struck me that Xi might just do the trick here.

What are your thoughts on the feasibility of this, can we embed Xi as a Widget in a Druid app?

**Comment by cmyr** [comment]
we can't do this exactly, but the plan is to adopt a bunch of stuff from xi as the basis for druid's text editing API, which should be powerful enough to build a text editor.

**Comment by davidrusu** [comment]
Figured it wouldn't be so easy ;) ok, thanks for your work on this framework here, it's good stuff

**Comment by cmyr** [comment]
Thanks, hope to have some text improvements to show soon!
