### ISSUE TITLE
Possibility of web renderering some day?

### ISSUE THREAD

**Issue by nuxeh** [xi-editor/druid#901]
Have been using Druid for a bit now and am really enjoying it, have just been thinking...

It seems to me that it should be possible to render in the same way Druid UIs render for desktop apps as a web interface too. I realise that might be a long way off, and I presume it has been considered before, I was just curious whether this might be a feasible idea in the long term, or if I'm getting carried away.

**Comment by xStrom** [comment]
There exists a rough implementation of this already. It will be part of the next release of druid, or you can check out [the examples](https://github.com/xi-editor/druid/tree/master/druid/examples/wasm) in the master branch.

**Comment by nuxeh** [comment]
That's amazing, thanks :D
