### ISSUE TITLE
Add a simple example of a custom widget with custom drawing

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#92]
I regularly want to play around with some drawing code, and it's annoying to have to bring up a new sample project each time. It would be nice if there was an example I could just tweak as needed.

I'll probably do this at some point; if someone else wants to first, they should feel free!

**Comment by futurepaul** [comment]
I [took a shot at this](https://github.com/futurepaul/druid/blob/custom-widget-example/examples/custom_widget.rs). I figured this would be a good chance to document some of the most common piet uses. Is this the sort of widget you had in mind?

**Comment by cmyr** [comment]
Yea that's great, would happily accept a PR.

**Comment by cmyr** [comment]
closed in #106
