### ISSUE TITLE
X11: Add support for the mouse wheel.

### ISSUE THREAD

**Issue by xStrom** [xi-editor/druid#921]
Currently the X11 backend only supports mouse move and clicks, however it should also support mouse wheel events. There's probably some useful inspiration in the GTK backend implementation.

**Comment by jneem** [comment]
I can take a stab at this in the near future.

Btw, is there a list somewhere showing what needs to be done to get X11 to parity with GTK?

**Comment by Finnerale** [comment]
@jneem there was, but I've now extracted all tasks into separate issues, all marked as `shell/x11`.
