### ISSUE TITLE
Double panic in test harness

### ISSUE THREAD

**Issue by xStrom** [xi-editor/druid#950]
If there's a panic (e.g. via `assert!`) after the [the following line](https://github.com/xi-editor/druid/blob/a480919f3f13932d14ebeb6cbfd2f21a1e4e0be2/druid/src/tests/harness.rs#L142):
```rust
// Harness::create_with_render
let piet = target.0.as_mut().unwrap().render_context();
```

Then the program crashes:
```
thread panicked while panicking. aborting.
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

This means that it's difficult to track down the exact test assertion that fails. Ideally we should track down the reason for the double panic and remove that. If that can't be done then `harness_closure` could return a `Result` via a custom `our_assert!` macro instead of panicking.

**Comment by cmyr** [comment]
ugh yea that's what the drop guard is for, to ensure we clean up that resource. What platform is this on?

**Comment by xStrom** [comment]
That's interesting. This is happening on my Windows 7. It's not a problem on Ubuntu 20.04.

**Comment by Finnerale** [comment]
Does this happen on macOS as well? This is indeed not a problem on Linux so I can't test #984 .

**Comment by xStrom** [comment]
No this does not happen on macOS.
