### ISSUE TITLE
rename WidgetPod::paint_with_offset to just 'paint'

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#962]
This has been a long-standing todo, and I think it makes sense; it's a bit of a gotcha right now.

What is currently 'paint' can get some other more annoying name.

**Comment by xStrom** [comment]
What's the benefit of the current `paint`? Just performance when the origin matches? I'm thinking how often does it even get used and for what purpose.

**Comment by cmyr** [comment]
I think that `paint` might get called by the others, after applying the transform? I'm not 100% sure though. Those names look good, maybe `paint_raw` instead of `paint_with_current_origin` but just spitballing.

**Comment by totsteps** [comment]
As per discussion here how I will rename things:
|Current Name|New name|
|-------|-------|
| paint|paint_raw|
|paint_with_offset| paint |
|paint_with_offset_always|paint_always|

Should we proceed with these renamings?

**Comment by xStrom** [comment]
Yeah I think those names are fine.

**Comment by totsteps** [comment]
Once the `paint_with_offset` is renamed to `paint` there will be name conflict at line [druid/src/core.rs:372 and 373](https://github.com/xi-editor/druid/blob/1cacd85f89edf76b10c688d077508c25bde19ff6/druid/src/core.rs#L372).

Not sure how to resolve this!?

**Comment by xStrom** [comment]
```
- their [`paint`] method.
+ [`Widget::paint`].
```
