### ISSUE TITLE
`Painter` not updating as expected

### ISSUE THREAD

**Issue by covercash2** [xi-editor/druid#988]
# Description
given some state:

```
pub struct State {
    string: String,
}
```
creating a `druid::widget::Painter` to indicate the state should dynamically change the style of the widget. we can also add a `druid::widget::Label` to represent the state.

with the `Label` added, the app acts as intended (a "good" state is when `string.len()` is even):

![draw working as expected with label](https://i.imgur.com/zYH2WdP.gif)

however, when the `Label` is absent, the `Painter` no longer updates as expected, when the text in the `TextBox` is updated:

![draw not repainting border when label is absent](https://i.imgur.com/I1aaNPe.gif)

however, unfocusing the window will trigger the `Painter` to draw correctly:

![draw repaints border on window focus](https://i.imgur.com/bZ2u9BG.gif)

# what we have so far
my env is... esoteric. Arch Linux 5.6.11, i3 + Xorg, GTK3 3.24.20, but i also reproduced this on my macbook, macOS Mojave 10.14.6.

gdb and ole fashioned print debugging show that the closure passed to `Painter` is being run -- color is updated, values are calculated, etc. --, but i haven't dug into the `ctx.stroke` or `ctx.fill` enough to know exactly what is happening, and i'm still learning the draw system in general (i'm pretty new to druid).

i worked up this minimal example, but my original widget was a simple file viewer, using a more complicated state including things like `PathBuf` and some homebrewed `druid::Data` types. the basic behavior is the same, though. anyway, i pressed on thinking that something else in the hierarchy might trigger the redraw, and i was right! but this seems like a bug, so i went ahead and opened an issue.

code: https://gist.github.com/covercash2/0ef3185cf25635900363da5b71e4e268
gifs: https://imgur.com/a/ausXF2u

**Comment by jneem** [comment]
This sounds like a partial invalidation issue, particularly since it fixes itself when you change focus. I'll take a look.
