### ISSUE TITLE
Towards less confusion over web support.

### ISSUE THREAD

**Issue by xStrom** [xi-editor/druid#999]
## Background
Druid supports targeting the web, however the naming we use in documentation is all over the place.

There are **web** and **Wasm**. Currently both are used pretty much as synonyms. I think we should be more precise with our terms to avoid confusing people.

### Web
Web is a really well known term and definitely delivers the message. Druid can run on the web. However the web supports multiple languages other than Wasm. Druid mostly runs via Wasm, although indirectly also via others. The distinction is that Wasm is involved at all, because it would also be possible to just transpile straight into JavaScript.

### WebAssembly
Wasm is less known but in some circles where it is known it can have a higher *cool factor* than plain *web*. Those who do know Wasm would probably guess that this means that druid runs on the web. However WebAssembly also [supports non-web targets](https://webassembly.org/docs/non-web/) which druid certainly does not. (*Not via Wasm anyway.*)

## Standardizing the terms
I think **web** is the better term to go with. Orders of magnitude of more people know what it means and I think it's also closer to the practical reality we have here - druid runs on the web and not on any other Wasm targets.

So whenever in documentation we need just a single word to describe this backend/capability we would use **web**. However when we're talking about it in more detail, it would be fine to say **web via Wasm** or describe that the **web** capability is achieved thanks to **Wasm**. That is to say, I'm not proposing on removing all mentions of **Wasm** - I'm just trying to limit it to contexts talking about **web** - so that when people see it used, they know that it has something to do with the web.

## Open for feedback
Did I miss something? Are there good reasons to go with a different route? Please comment.

**Comment by Finnerale** [comment]
Hm, it should certainly be made clear that druid requires WASM to run on the web (I think we do right?). Because that means we only support fairly up-to-date browser and druid won't be a good choice for building your IE app :sob: 

But that aside I think going with `web` is a good choice :+1:

**Comment by xStrom** [comment]
Yes I think it's a good idea to talk about Wasm when talking about the requirements of the web target.
